language: node_js

node_js:
  - "8"
services:
  - docker
before_install:
  - npm i -g npm
  - docker pull influxdb
  - docker run -d -p 8083:8083 -p 8086:8086 influxdb
addons:
  sauce_connect: true
script: npm test